### PR TITLE
Spring 5.2.9 to 5.3.4 via upgrade to Spring Boot 2.4.3 (nearly fully working)

### PR DESCRIPTION
**Pull request by duttonw**
This is a major departure from xml based spring for springboot auto wiring (including encryption module).

Still not complete (integration selenium tests not passing) but all other tests are now passing (without much change) other than class renames for mockito-all to mockito-core and hamcrest name clash corrections.

Also includes CSP dynamic script token injection thanks @tonymcneil for the initial work on that. I've also updated the gulp script to inject it into the pulled in swe4 templates as we now have script/link and inline being added via it.

Moved from spring source discreet version including to spring-boot bom dependancy managed imported pom. 
Added jackson-core due to miss-match version issue in keeping above cve flagged version.

Git commit plugin added so spring-boot health info can provide commit id and commit date etc (in simple version so it does not show email/usernames etc)

jetty removed for spring-boot:run 
selenium integration tests now only boots  email dumpster not jetty and email (since spring-boot:run is triggered before integration testing)

ftl freemaker files updated to ftlh which is auto escaped by default

properties converted to yml format for easier reading and reduced parent level duplications.

and much more

Still a draft and open to others to jump and help complete the work if i become delayed.

### CODE REVIEW

**Comment by bakersemail** [comment]
Hi Will, 

Great work on this! 

I'll need to check how compatible these changes are when used by our internal extension projects, as well as our infrastructure.

**Review by ThrawnCA — APPROVED** [review]

**Comment by duttonw** [comment]
Hi @bakersemail , have you been able to get integration tests to pass yet? I really want to get back to this but other things have been made higher priority.

Also, something i'd like your input on also is the shopping cart and safari problem.

Issue:
PAPI - Shopping Cart does not work on Safari including all iPhone browsers on latest version 

Desired outcome:
Mini-cart on PAPI need third-party cookie, which no longer works (can't do tracking of cookies)
 
Comments:
Affects perhaps 30% of attempted purchases for JP. Would need changes at client end as well if they use Shopping Cart and PAPI APIs rather than PRODI 

 Workaround on Mac is download Chrome browser

**Comment by duttonw** [comment]
Apple has made privacy no1 importance, the way the shopping cart functionality works is now totally broken, there might a way to make it work again.

Google chrome on iphone X and it also shows the same behavior as safari on mac and iphone (both also tested). The reason for other browsers working similar to safari is due to Apple enforcing only one browser back-end engine on the iphone, the rest skin the front of house etc. see https://www.digitalcommerce360.com/2017/05/02/apples-dirty-little-secret-about-chrome/ 

Details of why below:
https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/ 
https://robinlinus.github.io/socialmedia-leak/

By 2022, this could possibly impact over 75% of users from accessing the JP Shop.

@bakersemail  will this also effect your applications?

**Comment by bakersemail** [comment]
Hi William,

I have been able to get this working properly. I bumped the version to 2 to allow us to merge this into master. Visiting http://localhost:8091/test works and adds to cart. 

The 3rd party cookie issue has been a long running problem with Safari, later Firefox and might even come with Chrome soon as I believe they are planning on blocking this too. I dont think we have a proper solution to this and may need to allow PAPI clients to pull cart state from server-side to render themselves. Happy to chat further on Teams if you'd like.

**Comment by bakersemail** [comment]
Hi Will, This does effect our apps. We work around this by having a separate checkout button which directs the customers through the synchronise function. We also plan to remove the shopping cart aside altogether unless we get a solution to the 3rd party cookie limitations.

**Review by bakersemail — APPROVED** [review]
Looks good, perhaps remove commented out code.

**Pull request merged**
